### ISSUE TITLE
Example for Vue

### ISSUE THREAD

**Issue by otavio-paganotti** [Wootric/spa-examples#5]
Could you create a configuration example for Vue.js?

**Comment by prabhatjha** [comment]
Hi @otavio-paganotti Sure , we will. Are you blocked on this?

**Comment by otavio-paganotti** [comment]
Yes, I could not transcribe the examples in Angular and React in Vue, and this is my current activity on the Jira. Haha

**Comment by prabhatjha** [comment]
Ok, we will try to push one example next week. By the way simplest Wootric integration is simply adding our code snippet on `index.html` as described here https://docs.wootric.com/javascript/#the-simplest-integration.

**Comment by otavio-paganotti** [comment]
Ok. Thanks! I'll be waiting.

**Comment by otavio-paganotti** [comment]
I'm still waiting, hahaha

**Comment by matrixOnline** [comment]
> I'm still waiting, hahaha

me 2....

**Comment by ambarwootric** [comment]
Hi @otavio-paganotti and @matrixOnline we are sorry for the delay. Please find the `vue js` working examples under https://github.com/Wootric/spa-examples/tree/master/vuejs.

Please free to ask any further questions through our customer support. We would love to help you.
